[package]
name = "ll65"
version = "0.1.0"
authors = ["Scitoshi Nakayobro <matthewtpeterson1@gmail.com>"]
edition = "2018"

[dependencies]
paste = "0.1.5"
clap = "2.33.0"

[[bin]]
name = "ll65"
file = "main.rs"